version: 2

models:
  - name: int_users__transacoes
    description: Representa transações realizadas pelos usuários
    columns:
      - name: cd_transacao
        description: Código único da transação
      - name: tm_transacao
        description: Data e hora da transação (UTC 0)
      - name: nm_captura
        description: Dispositivo de captura (POS, Tapton ou Link de pagamento)
      - name: nm_bandeira_cartao
        description: Bandeira do cartão
      - name: nm_metodo_pagamento
        description: Método de pagamento
      - name: nm_estado_transacao
        description: Estado da transação (valores aceitos. paid, refused, refunded e chargedback)
      - name: vl_transacao
        description: Valor da transação (R$)
      - name: cd_usuario
        description: Código único do usuário
      - name: nm_estado_usuario
        description: Estado do usuário
      - name: nm_cidade_usuario
        description: Cidade do usuário
